version: '3'
services:
  core:
    network_mode: host
    build: .
    volumes:
    - .:/usr/src/core
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    depends_on:
      - clickhouse
    command: start #prepare-database
    restart: always

  clickhouse:
    build: ./clickhouse-config/
    ports:
      - "9000:9000"
      - "8123:8123"
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./clickhouse:/var/lib/clickhouse:Z
    restart: always

  grafana:
    network_mode: host
    build: ./grafana/
    depends_on:
      - clickhouse
    ports:
      - "3001:3000"
    restart: always

  clickhouse_client:
    network_mode: host
    image: yandex/clickhouse-client:latest
    depends_on:
      - clickhouse
