version: '3'
services:
  core:
    network_mode: host
    build: .
    volumes:
    - .:/usr/src/core
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    depends_on:
      - clickhouse
      - parity
    command: prepare-database

  clickhouse:
    image: yandex/clickhouse-server:18.12.17
    ports:
      - "9000:9000"
      - "8123:8123"

  parity:
    image: parity/parity:stable
    ports:
      - "8545:8545"
    command: --mode=active --jsonrpc-interface=all --tracing=on --db-path /db
    volumes:
      - ./parity:/db:Z

  tabix:
    build: ./tabix/
    depends_on:
      - clickhouse
    ports:
      - "8080:80"
