version: '3'
services:
  cyberdrop:
    network_mode: host
    build: .
    volumes:
    - .:/usr/src/core
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    depends_on:
      - elasticsearch
  elasticsearch:
    build: elasticsearch/.
    ports:
    - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g