version: '3'
services:
  core:
    network_mode: host
    build: .
    volumes:
    - .:/usr/src/core
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    depends_on:
      - clickhouse
      - parity
    command: prepare-database

  clickhouse:
    build: ./clickhouse-config/
    ports:
      - "9000:9000"
      - "8123:8123"
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./clickhouse:/var/lib/clickhouse:Z
    restart: always

  parity:
    image: parity/parity:stable
    ports:
      - "8545:8545"
    command: --mode=active --jsonrpc-interface=all --tracing=on --db-path /db
    volumes:
      - ./parity:/db:Z

  grafana:
    network_mode: host
    build: ./grafana/
    depends_on:
      - clickhouse
    ports:
      - "3000:3000"

  clickhouse_client:
    network_mode: host
    image: yandex/clickhouse-client:latest
    depends_on:
      - clickhouse
