version: '3'
services:
  cyberdrop:
    network_mode: host
    build: .
    volumes:
    - .:/usr/src/core
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    depends_on:
      - clickhouse
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
    - "9000:9000"