version: '3'
services:
  cyberdrop:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/usr/src/core
    environment:
      WAIT_HOSTS: elasticsearch:9200
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
    - "9200:9200"