version: '3'
services:
  core:
    network_mode: host
    build: .
    volumes:
    - .:/usr/src/core
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    depends_on:
      - clickhouse
      - parity
    command: --operation prepare-database

  clickhouse:
    image: yandex/clickhouse-server:18.12.17
    ports:
      - "9000:9000"

  parity:
    image: parity/parity:stable # TODO check version
    ports:
      - "8545:8545"
    command: --mode=active --pruning=archive --jsonrpc-interface=all

#  tabix:
#    image: spoonest/clickhouse-tabix-web-client
#    depends_on:
#      - clickhouse
#    ports:
#      - "8080:8080"

